### ISSUE TITLE
nice tool , just need help

### ISSUE THREAD

**Issue by saberzaid** [penetrarnya-tm/WeaponizeKali.sh#2]
hello . thanks for this tool it will save alot of time 

i notice first there is a tool cant be downloaded durring the instllation of www , for example

[-] Failed to download raw file: sessiongopher.ps1

and i also cant run any tool in the tools folder from any location , this is my file setting for sudoers

Defaults        env_reset
Defaults        mail_badpass
Defaults        secure_path="/home/rohanexe/.local/bin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

# Host alias specification

# User alias specification

# Cmnd alias specification

# User privilege specification
root    ALL=(ALL:ALL) ALL

# Allow members of group sudo to execute any command
%sudo   ALL=(ALL:ALL) ALL

# See sudoers(5) for more information on "@include" directives:

@includedir /etc/sudoers.d
www-data ALL=(ALL:ALL) NOPASSWD:ALL

some error i found also durring the process:

[WPNZKL] Installing ldapdomaindump
[+] Cloned repository: ldapdomaindump
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.                                                                                    
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

**Comment by snovvcrash** [comment]
Hello there!

Thanks for the feedback! In regard to your questions:

> [-] Failed to download raw file: sessiongopher.ps1

That's weird because the download URL for SessionGopher [is alive](https://github.com/Arvanaghi/SessionGopher/raw/master/SessionGopher.ps1). If some scripts or binaries from `www` fail to download, try removing the whole `www` directory and doing it again with `bash WeaponizeKali.sh -w`.

> i also cant run any tool in the tools folder from any location

Some tools, that are not installed with pip/pipx or which are shipped as a single binary, should be launched from their corresponding directories in `tools`.

> ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

Fixed that error, thanks!
